helpsupply/helpsupply

- src/components/HCPSignupFinish.js
BE CAREFUL WITH THIS ONE - review first. I only meant to make changes in the return output. All the functional edits here are because I had to merge a conflict with an incoming change.
> Beautify HCPSignupFinish

- src/components/EntryPortal.js
- Empty search box does not go anywhere
- Only clicking on a selected Hospital OR pressing "enter" when a hospital is selected does anything happen.
> Fixed empty entries in Home Page Hospital Search

- src/components/Button/Button.styles.js
- src/components/InputText/InputText.styles.js
- src/components/InputText/index.js
Creates an input text with focus styles and fancy label transforms.
> Input text

- .prettierrc
- package.json
- yarn.lock
- installs [prettier](https://prettier.io/)
- adds a pre-commit hook to format files using [pretty quick](https://github.com/azz/pretty-quick)
- formats all files
> Prettier configuration

- src/components/Button/Button.styles.js
- src/components/Button/constants.js
- src/components/Button/index.js
- src/components/InputText/InputText.styles.js
- src/components/InputText/index.js
- src/components/StyleGuide.js
- src/components/Text/Text.js
- src/lib/theme/colors.js
I was working off an archived design so this updates the colors and designs for buttons + inputs
> update styles for button + input

- src/components/StyleGuide.js
- src/components/Textarea/Textarea.styles.js
- src/components/Textarea/index.js
- src/lib/theme/accessibility.js
- src/lib/theme/index.js
Creates an input text with focus styles
> Textarea component

- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputDropdown/index.js
- src/components/StyleGuide.js
- src/static/icons/chevron.svg
> Custom dropdown

- src/components/Card/Card.styles.js
- src/components/Card/index.js
- src/components/StyleGuide.js
- src/components/Text/Text.styles.js
- src/components/Text/constants.js
- src/components/Text/index.js
- card component + styles
- refactor of text component to match other stylistic patterns
- adds `styles` prop to text component to add additional styling in more complex components
> Card component + refactor text component

- src/App.js
- src/components/Autosuggest/Autosuggest.styles.js
- src/components/Autosuggest/index.js
- src/components/Box/Box.styles.js
- src/components/Box/index.js
- src/components/Button/index.js
- src/components/Card/index.js
- src/components/StyleGuide.js
- src/components/Text/index.js
- src/index.css
- src/pages/EntryPortal.js
- src/pages/Request/Request.styles.js
- src/pages/Request/index.js
- src/static/icons/back-circle.svg
Implements the current search index with the autosuggest input.
Started this work on the route /start in order to keep everything else as is and gradually implement the new UI.
> City or healthcare facility form

- src/components/Header/Header.styles.js
- src/components/Header/index.js
- src/pages/request.js
- src/static/icons/plus.svg
> Header component

- package.json
- src/components/Card/index.js
- src/components/InputText/InputText.styles.js
- src/components/InputText/index.js
- src/components/Request/Request.styles.js
- src/components/Request/index.js
- src/components/StyleGuide.js
- src/components/Text/Text.styles.js
- src/components/Text/constants.js
- src/components/Text/index.js
- src/lib/utils/datetime.js
- src/lib/utils/number.js
- yarn.lock
- request component
- added util files
> Request component

- src/App.js
- src/containers/SupplyForm.js
- src/pages/supplies_new.js
Just the bare bones form for new supply request.
Need to figure out where/how we will get the data for the dropdowns.
You can access the page via localhost:3000/new/admin/supply/50441
> New Supply form

- src/App.js
- src/components/Checkbox/Checkbox.styles.js
- src/components/Checkbox/index.js
- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputDropdown/index.js
- src/components/InputText/InputText.styles.js
- src/components/Note/index.js
- src/components/Request/index.js
- src/components/Text/Text.styles.js
- src/components/TextArea/index.js
- src/containers/DropSiteForm.js
- src/containers/FacilityForm.js
- src/containers/FindFacility.js
- src/data/states.js
- src/lib/theme/colors.js
- src/pages/facility_new.js
- src/static/icons/check.svg
- src/static/icons/plus-circle.svg
Creates a form for adding a new facility. Does not include integration.
> New facility form

- .gitignore
Add editor configs to gitignore.
> add .idea files to gitignore

- src/components/HCPSignupFinish.js
- src/components/InputText/index.js
- src/containers/DropSiteForm.js
- src/lib/firebaseBackend.js
- src/pages/dropsite_new.js
Adds more details to the dropsite when form is filled out and redirects to the facility page.
> Integrate dropsite form

- src/lib/utils/datetime.js
- src/lib/utils/datetime.test.js
- src/lib/utils/number.test.js
Issue #83 
A bunch of tests. Let me know if you'd like to see anything else in here.
> chore(tests): add tests for utils

- src/components/FacilityConfirmation/FacilityConfirmation.styles.js
- src/components/FacilityConfirmation/index.js
- src/components/Form/index.js
- src/components/HCPSignupFinish.js
- src/components/InputText/index.js
- src/containers/DropSiteForm.js
- src/containers/FacilityForm.js
- src/lib/firebaseBackend.js
- src/lib/theme/colors.js
- src/lib/utils/datetime.test.js
- src/lib/utils/number.test.js
- src/pages/dropsite_admin.js
- src/pages/dropsite_new.js
- src/pages/supplies_new.js
- src/static/icons/green-check.svg
Integrates adding a new facility with the new fields in the database. Should display the confirmation screen, then on next, route to the signup with the ID of the newly created facility
> New facility integration

- src/App.js
Found an extra `path="/signup/:dropsite?"`
> Found a duplicate route in App.js

- src/components/Autosuggest/Autosuggest.styles.js
- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputDropdown/index.js
- src/components/InputText/InputText.styles.js
- src/components/TextArea/TextArea.styles.js
- src/lib/theme/borders.js
- src/lib/theme/index.js
- src/lib/theme/reset.js
* Created a `Borders` file for some reused borders.
* Added `selectReset` to the `resets` area.
* Setup `InputDropdown` to use a native select.
> Switch dropdown component to use native select

- src/constants/routes.js
- src/pages/entry.js
Issue #103
- Update to latest copy in Figma
- Remove donate link, replace with request supplies link
- Minor updates to margins to match design
> feat(start page): edits to copy and routes

- package.json
- src/App.js
- src/components/Autosuggest/Autosuggest.styles.js
- src/components/Form/index.js
- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputDropdown/index.js
- src/components/InputText/InputText.styles.js
- src/components/InputText/index.js
- src/containers/DropSiteForm.js
- src/containers/EmailForm.js
- src/containers/FacilityForm.js
- src/containers/SupplyForm.js
- src/lib/theme/height.js
- src/lib/theme/index.js
- src/lib/utils/validations.js
- src/lib/utils/validations.test.js
- yarn.lock
Implements react hook form in our Form component. We can access the register function via context and name will be required in order to register the component to the form.
Right now the required messaging is included in the inputs and we can explicitly mark an input as optional to remove this messaging. See the email form component to see how we can use custom validation.
Going forward if we need to add custom validation the input component will accept `validation` as a prop.
> Smart form component

- src/components/HCPSignupFinish.js
Redirects user to the facility page if requests for that facility exist.
If not, direct them to the request supplies form.
> redirect user if requests exist

- src/components/Form/Form.styles.js
- src/components/layouts/Page/Page.styles.js
- src/components/layouts/Page/index.js
- src/index.css
makes some layout changes to make right content scrollable. waiting to hear from design about where we want the right content to align.
> Make content scrollable

- src/components/BackButton/BackButton.styles.js
- src/components/layouts/Page/Page.styles.js
- src/components/layouts/Page/index.js
- src/pages/entry.js
Closes #113 #71 
I want to believe there is a way to manage this layout with pure CSS (and I got really close!), but in the end I had to resort to using JS to get a measurement to set the padding for the right column.
> chore(page): set desktop alignment

- package.json
- src/index.js
Adds basic support for IE11.
https://app.clubhouse.io/helpsupply/story/49/site-does-not-display-in-ie11-windows-10
> feat(global): add ie11 support

- src/components/Alert/InvalidEmail.js
- src/components/Alert/index.js
- src/components/Anchor/index.js
- src/components/Autosuggest/Autosuggest.styles.js
- src/components/Dropsite/Admin.js
- src/components/HelpFooter.js
- src/components/NewDropSite.js
- src/containers/EmailForm.js
- src/containers/FacilityForm.js
We were mixing html anchors with dynamic routing. There are probably more instances of this that need to be converted over.
> fix(links): use react-router Link for page navigation

- src/components/Anchor/Anchor.styles.js
- src/components/Autosuggest/Autosuggest.styles.js
- src/components/Button/Button.styles.js
- src/components/Checkbox/Checkbox.styles.js
- src/components/Dropsite/DropSiteAdmin.styles.js
- src/components/Header/Header.styles.js
- src/components/Header/LargeHeader.styles.js
- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputText/InputText.styles.js
- src/components/IntroContent/IntroContent.styles.js
- src/components/IntroContent/index.js
- src/components/Request/Request.styles.js
- src/components/TextArea/TextArea.styles.js
- src/components/layouts/Page/Page.styles.js
- src/containers/FindFacility.js
- src/lib/theme/colors.js
I know emotion.js supports theming, but that seemed a little overfill for our current needs.
* In `colors.js`, made `PRIMARY` and `SECONDARY` attribs.
* Updated all uses of `CORAL` and `CORAL_30` with primary and secondary.
> Simple color theme values

- src/components/Autosuggest/Autosuggest.styles.js
Add a cursor to the auto-suggest for facilities.
> Add cursor pointer to desktop autosuggest

- src/pages/dropsite_new.js
I think this is the last one of these 🤞
> chore(dropsite): add loading state to new dropsite screen

- package.json
- src/components/Button/Button.styles.js
- src/components/Button/constants.js
- src/components/Button/index.js
- src/components/Dropsite/Admin.js
- src/components/Dropsite/DropSiteAdmin.styles.js
- src/components/Loader/Loader.styles.js
- src/components/Loader/index.js
- src/components/Modal/Modal.styles.js
- src/components/Modal/index.js
- src/components/Request/DeleteRequestModal.js
- src/components/Request/DeleteRequestModal.styles.js
- src/lib/theme/animations.js
- src/lib/theme/colors.js
- src/lib/theme/index.js
- src/locales/en.json
- src/pages/dropsite_admin.js
- src/static/icons/loader.svg
- yarn.lock
Closes: https://app.clubhouse.io/helpsupply/story/72/add-delete-request-functionality
Here we are adding the ability to delete requests. I added `react-modal` to handle the confirmation overlay and it seems to work really well!
I had to tweak the button styles to support the outlined version of the `PrimaryButton` that is coming in with the new design.
I may have gone a step too far with the loading state that appears in the request list, but it will be simple to remove if we deem that the correct decision.
> feat(requests): adds delete requests functionality

- src/components/Button/Button.styles.js
- src/components/Form/index.js
- src/components/InputText/InputText.styles.js
- src/components/StyleGuide/index.js
- src/components/TextArea/TextArea.styles.js
- src/lib/theme/borders.js
- src/lib/theme/colors.js
- src/locales/en.json
* Updating some of the styles have changed slightly since when development first started
* Also created a basic local label for the Form button to accommodate new designs ('Please complete form')
* Updated style guide to work on mobile.
> Update styles and form label

- src/lib/firebaseBackend.js
- src/lib/organizations/index.js
Just clearing out a few warnings.
> Chore: linter warnings

- functions/babel.config.js
- functions/jest.config.js
- functions/main.js
- functions/main.test.js
- functions/package-lock.json
- functions/package.json
- src/lib/firebaseBackend.js
- src/lib/organizations/index.js
- src/lib/organizations/kinds.js
- src/lib/organizations/manyc.js
Largely making this a pull request so that I can check that the linters all pass, but comments welcome!
This finishes up the full flow so that:
1. Someone calls `backend.saveServiceRequest(...)`
2. A firebase function is called asynchronously from database notifications:
a. We look up the right organization to handle the request
b. We call the organization's DeliverRequest function
c. The DeliverRequest function (usually) posts to a WebHook
d. Depending on success/failure, we modify `request.status` to be `distributed` or `error`
Tests are included (which took the bulk of the work... because JS modules are terrible), and are run via `npm run test` in the functions folder.
If 3rd party webhooks often fail, I'll likely write a recurring function to look for failed requests and retry them.
> Complete framework for Request Distribution

- src/components/Anchor/index.js
- src/components/Confirmation/ContactConfirmation.js
- src/components/Confirmation/FacilityConfirmation.js
- src/components/Confirmation/SupplyConfirmation.js
- src/components/Dropsite/Admin.js
- src/components/Form/index.js
- src/components/HCPSignupFinish.js
- src/components/LearnMore/About.js
- src/components/LearnMore/FAQ.js
- src/components/Request/index.js
- src/components/SignupFinish.js
- src/components/StyleGuide/index.js
- src/containers/ContactForm.js
- src/containers/DropSiteForm.js
- src/containers/EmailForm.js
- src/containers/FacilityForm.js
- src/containers/FindFacility.js
- src/containers/ServiceContactForm.js
- src/containers/ServiceTypeForm.js
- src/containers/SupplyForm.js
- src/i18n.js
- src/locales/en.json
- src/pages/signup_confirmation.js
- refactor format of translation json to be more dev friendly
- standardize naming - more work could probably be done here but this is a good first pass :)
> Refactor translation json

- src/lib/utils/validations.js
- adds zip code and empty field validation to utils
> Form validation

- src/App.js
- src/components/AdditionalContact/AdditionalContact.js
- src/components/AdditionalContact/AdditionalContact.styles.js
- src/components/AdditionalContact/index.js
- src/components/Checkbox/Checkbox.styles.js
- src/components/Form/CreateFormFields.js
- src/components/InputDate/InputDate.js
- src/components/InputDate/InputDate.styles.js
- src/constants/Routes.js
- src/containers/AdditionalInfoForm.js
- src/containers/GroceryFormDate.js
- src/containers/GroceryFormItems.js
- src/containers/GroceryFormLocation.js
- src/containers/ServiceContactForm.js
- src/containers/ServiceFacilityForm.js
- src/containers/ServiceTypeForm.js
- src/data/neighborhoods.js
- src/lib/organizations/dummy.js
- src/locales/en.json
- src/pages/service_additional_info.js
- src/pages/service_grocery.js
* Added routes and pages for Grocery forms
* Added route and page for Additional Info form
* Updated Contact form translation fields
* Slightly adjusted checkbox style
* Created a dummy neighborhoods data file
* Created a dummy organization record to fix error in `lib/organizations`
* Incorporated `InputDate` into the `Formbuilder`
> Grocery forms

- .eslintignore
- ignore linting for `src/lib/organizations` to fix deploys
> Fix deploys

- src/App.js
- src/components/Dashboard/OpenServiceRequests.js
- src/components/Dashboard/UserDashboard.js
- src/components/Dashboard/UserDashboard.styles.js
- src/components/Dropsite/Requests.js
- src/components/Request/index.js
- src/components/Services/GroceryRequest.js
- src/components/Services/Request.styles.js
- src/constants/Routes.js
- src/lib/constants/urgency.js
- src/lib/firebaseBackend.js
- src/lib/utils/datetime.js
- src/locales/en.json
- src/pages/dashboard.js
Creates the dashboard page.
I'm done for the night but would like to put this up for PR so i can get eyes on it ASAP and pick it back up tomorrow since I don't have time during the day to work on this.
Styling needs to be done on the request buttons, and there are some notes for things that still need to be done (only grocery request card has been completed) and integration for deleting a request is not done yet.
> create dashboard page

- src/App.js
- src/constants/Routes.js
- src/containers/EmotionalFormDate.js
- src/containers/EmotionalFormType.js
- src/containers/ServiceTypeForm.js
- src/locales/en.json
- src/pages/service_emotional.js
* Created routes and page for mental-health forms.
* Commented out unused vars in `manyc.js` that were breaking build.
* Any thoughts on making the form values for generic/reusable are welcome. Looping through the days of the week manually feels a little clunky, but trying to just get it all done.
> Mental-health forms

- firestore.rules
- src/components/Confirmation/ContactConfirmation.js
- src/containers/ChildcareFormLocation.js
- src/containers/GroceryFormLocation.js
- src/containers/PetcareFormLocation.js
- src/containers/ServiceContactForm.js
- src/containers/ServiceTypeForm.js
- src/lib/constants/contact.js
- src/lib/constants/languages.js
- src/lib/constants/services.js
- src/lib/constants/urgency.js
- src/lib/firebaseBackend.js
- src/lib/utils/services.js
- src/lib/utils/urgency.js
- src/locales/en.json
- src/pages/contact.js
- src/pages/contact_confirmation.js
https://app.clubhouse.io/helpsupply/story/182/contact-form-integration
* Some user metadata isn't part of the regular firebase user, so this approach uses an auxiliary `serviceuser` collection in firebase to hold data such as: contactPreference, languagePreference.
* Created `LANGUAGES` and `CONTACT_PREFERENCES` for some dropdown values that are reused.
* Created constants and utils for urgency and service options, `buildUrgencyOptions` and `buildServicesOptions`.
* Wired up `/contact/` and `/contact/confirmation` to firebase.
* Fixed validation on `ServiceContactForm`.
> Contact integration, contact form validation

- src/App.js
- src/components/Card/Card.styles.js
- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/ServiceReview.styles.js
- src/constants/Routes.js
- src/containers/AdditionalInfoForm.js
- src/containers/ServiceConfirmation.js
- src/containers/ServiceReview.js
- src/lib/utils/datetime.js
- src/locales/en.json
- src/pages/service_additional_info.js
- src/pages/service_confirmation.js
- src/pages/service_review.js
this is a bit of a WIP but i'd love some thoughts before i go too far down a path with these review pages <3
- sets up service review + confirmation pages
- generic styles for service review page
- review grocery request component
> Grocery service review

- src/components/Checkbox/index.js
- src/components/Dashboard/OpenServiceRequests.js
- src/components/Services/ChildCareRequest.js
- src/components/Services/GroceryRequest.js
- src/components/Services/Request.styles.js
- src/containers/ChildcareFormDate.js
- src/containers/ChildcareFormDetails.js
- src/containers/ChildcareFormLocation.js
- src/containers/ChildcareFormOptions.js
- src/containers/GroceryFormDate.js
- src/containers/GroceryFormItems.js
- src/containers/GroceryFormLocation.js
- src/lib/firebaseBackend.js
- src/pages/dashboard.js
- src/pages/service_childcare.js
- src/pages/service_grocery.js
Creates child care card, fills input fields when a user wants to edit (only for grocery + childcare so far)
Fixes the way children were being saved. You couldn't add more than one child on the backend so this creates a map of children
Also fixes the delete (was using deleteSupplyRequest)
> Grocery + Childcare edit, card, delete

- src/components/Confirmation/ServiceConfirmation.js
- src/components/Confirmation/ServiceConfirmation.styles.js
- src/components/Confirmation/index.js
- src/components/LearnMore/FAQ.js
- src/components/ServiceReview/Childcare.js
- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/MentalHealth.js
- src/components/ServiceReview/Petcare.js
- src/containers/ServiceConfirmation.js
- src/containers/ServiceReview.js
- src/lib/utils/datetime.js
- src/locales/en.json
- src/pages/service_confirmation.js
- scaffold for all service review pages
- beginning of service confirmation page (wip)
> Service review + confirmation setup

- src/components/Confirmation/Confirmation.styles.js
- src/components/Confirmation/OrganizationConfirmation.js
- src/components/Confirmation/ServiceConfirmation.js
- src/components/Confirmation/ServiceConfirmation.styles.js
- src/containers/ServiceReview.js
- src/locales/en.json
- service confirmation page
- still outstanding: linking up real organization data
> Service confirmation page

- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/MentalHealth.js
- src/locales/en.json
- wires up mental health service review page
> Mental health service review

- src/App.js
- src/components/Confirmation/ContactConfirmation.js
- src/constants/Routes.js
- src/containers/ServiceLocationForm.js
- src/locales/en.json
- src/pages/service_location.js
- src/pages/service_type.js
- setup for zip code / service location form
- outstanding: needs to be integrated with current user, need to check against zip code entered for valid service types
> Service location (zip code) form

- src/components/ServiceReview/Childcare.js
- src/components/Services/ChildCareRequest.js
- src/lib/utils/strings.js
- src/locales/en.json
- childcare service review page
> Childcare service review page

- src/components/SignupFinish.js
signup finish link from email -> no contact -> contact info page
signup finish link from email -> has contact and no requests -> service location page
signup finish link from email -> has contact and has requests -> user dashboard
> Reroute existing user

- src/components/Dashboard/OpenServiceRequests.js
- src/components/Dashboard/UserDashboard.js
- src/components/Dashboard/UserDashboard.styles.js
- src/components/Services/ChildCareRequest.js
- src/components/Services/GroceryRequest.js
- src/components/Services/MentalHealthRequest.js
- src/components/Services/Request.styles.js
- src/components/SignupFinish.js
- src/containers/AdditionalInfoForm.js
- src/containers/ChildcareFormDate.js
- src/containers/ChildcareFormDetails.js
- src/containers/ChildcareFormLocation.js
- src/containers/ChildcareFormOptions.js
- src/containers/EmotionalFormDate.js
- src/containers/EmotionalFormType.js
- src/containers/GroceryFormDate.js
- src/containers/GroceryFormItems.js
- src/containers/GroceryFormLocation.js
- src/containers/PetcareFormDetails.js
- src/containers/PetcareFormLocation.js
- src/lib/constants/options.js
- src/lib/utils/strings.js
- src/locales/en.json
- src/pages/dashboard.js
this wraps up https://app.clubhouse.io/helpsupply/story/127/your-requests-page since we aren't implementing pet care
> Remove edit/delete, fix timestamp, add mental health card, add contact info to dashboard

- src/components/Dashboard/UserDashboard.js
- src/components/Services/ChildCareRequest.js
- src/components/SignupFinish.js
- src/lib/firebaseBackend.js
Just a few random fixes.
* Used `Confirmation/SubRow` instead of `Card` because the `Note` and `Change` cta are vertically aligned and those components seem to do the same thing right now.
* Swapped `handleRequestSupplies ` for`handleRequestService`. The cta takes you to `/services` then.
* Nested `<p>` error.
* Added a `.catch((error)` which at least keeps the page from totally breaking.
* Added more helpful error messaging to a backend method.
> chore: fixing a couple of small errors, handling errors

- src/App.js
- src/components/Dashboard/OpenServiceRequests.js
- src/components/EntryContent/Intro.js
- src/components/ServicesList/ServicesList.styles.js
- src/components/ServicesList/index.js
- src/constants/Routes.js
- src/containers/AvailableServices.js
- src/containers/EmailForm.js
- src/containers/FacilityForm.js
- src/containers/ServiceLocationForm.js
- src/locales/en.json
- src/pages/service_location.js
- src/pages/service_location_available.js
- content + flow adjustments for entry flow
- i need help > service location form > available services > facility form > email sign up
> Entry flow updates

- src/App.js
- src/components/EntryContent/Intro.js
- src/constants/Routes.js
- src/containers/LoginForm.js
- src/locales/en.json
- src/pages/login.js
- returning user entry flow adjustments
- i already have open requests > login > email sent
- reusing the email sign up form logic for logging in 🤷
> Returning user entry flow

- src/components/Confirmation/ContactConfirmation.js
after contact confirmation send user to service flow
> Fix contact confirmation route

- src/components/Confirmation/OrganizationConfirmation.js
- src/components/Confirmation/ServiceConfirmation.js
- src/lib/organizations/details.js
- src/locales/en.json
- created organization details file
- map service type to organization and integrate into confirmation screen
> Link up organization data

- src/components/Confirmation/SignUpConfirmation.js
- src/components/Confirmation/SignUpConfirmation.styles.js
- src/pages/signup_confirmation.js
- noticed that the sign up confirmation was using a different layout than other confirmation screens so i refactored
- removed bold styling from email (looks like this was updated at some point)
> Refactor sign up confirmation

- src/App.js
- src/pages/login.js
> Fix login page

- src/App.js
- src/constants/Emails.js
- src/constants/Routes.js
- src/containers/ServiceLocationUpdateForm.js
- src/locales/en.json
- src/pages/service_location_update.js
> Update zip code form

- src/components/LearnMore/FAQ.js
- src/components/LearnMore/Partners.js
- remove unused content
- update hardcoded values
> Update Learn More

- src/containers/ServiceLocationForm.js
- src/containers/ServiceLocationUpdateForm.js
- src/containers/ServiceTypeForm.js
- src/pages/service_location_update.js
* Wire up the location update page at: http://localhost:3000/service-location/update
* If valid zip with services available, update their user record and send them back to the `/services` page.
> feat: wire-up the location update page

- src/components/Header/LargeHeader.js
- src/components/Header/index.js
- link logo in header to home page
- update a used in mobile header to use anchor component
> Add link to logo

- src/App.js
- src/components/ServiceReview/Childcare.js
- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/MentalHealth.js
- src/containers/ChildcareFormDate.js
- src/containers/ChildcareFormDetails.js
- src/containers/ChildcareFormLocation.js
- src/containers/ChildcareFormOptions.js
- src/containers/GroceryFormDate.js
- src/containers/GroceryFormItems.js
- src/containers/GroceryFormLocation.js
- src/pages/contact_confirmation.js
- src/state/StateProvider.js
- src/state/persistState.js
- src/state/reducer.js
> reroute back to review after editing a request

- src/components/ServiceReview/Grocery.js
- src/components/Services/GroceryRequest.js
forgot to update where we display the grocery delivery date
> convert new date format correctly when displaying

- src/state/StateProvider.js
forget to check both previous state and current in order to reset the redirect to review flag
> check prev should redirect AND current

- src/components/AdditionalCta/AdditionalCta.js
- src/containers/GroceryFormLocation.js
- src/locales/en.json
https://app.clubhouse.io/helpsupply/story/236/additional-contact-forms-missing-remove-link
* Add the 'remove' button the to additionalContact header.
* Have the button close that port of the form and reset the field values.
> Additional contact - add `remove` button

- src/containers/EmailListForm.js
- src/lib/firebaseBackend.js
* Submitting an email here:
http://localhost:3000/service-location/unavailable
* Should appear in the `emaillist` collection in firebase.
> Email List submit

- src/components/Dashboard/OpenServiceRequests.js
- src/components/ServiceReview/MentalHealth.js
- src/components/Services/ChildCareRequest.js
- src/components/Services/GroceryRequest.js
- src/components/Services/MentalHealthRequest.js
- src/lib/theme/services.js
https://app.clubhouse.io/helpsupply/story/277/requests-page-update-mentalhealth-to-emotional-support
* Made a utility to map the service kind to the pretty title.
> fix: update Mentalhealth to Emotional Support

- src/containers/ServiceReview.js
- src/lib/firebaseBackend.js
- src/pages/service_review.js
https://app.clubhouse.io/helpsupply/story/409/generate-json-of-request-details-for-email-template
Add details to the request confirmation email. Format contact information and handle each service type.
> feat: add details for confirmation email

- src/lib/firebaseBackend.js
We can use this method to send login emails for returning users.
> feat: backend method for sending login emails

- src/components/Form/Form.styles.js
- src/containers/ServiceLocationForm.js
fixes [ch360](https://app.clubhouse.io/helpsupply/story/360/what-is-your-zip-code-copy)
- update service location button label
- update global form description styles
> Update service location form

- src/locales/en.json
fixes [ch358](https://app.clubhouse.io/helpsupply/story/358/homepage-copy)
> Update home page copy

- src/App.js
- src/constants/Routes.js
- src/containers/EmailListForm.js
- src/locales/en.json
- src/pages/signup_welcome.js
- sets up welcome page for new users
- renames email list confirmation page route for less confusion
> Welcome back page for new users

- src/App.js
- src/components/Confirmation/SignUpConfirmation.js
- src/components/HCPSignupFinish.js
- src/components/LoginFinish.js
- src/components/SignupFinish.js
- src/constants/Routes.js
- src/containers/EmailForm.js
- src/containers/FacilityForm.js
- src/containers/ServiceContactForm.js
- src/lib/firebaseBackend.js
- src/pages/login_approve.js
- Adds welcome interstitial
- Properly saves facility (both in localstorage and serviceuser)
> Fix login flow

- src/components/ServiceReview/Grocery.js
- src/containers/GroceryFormLocation.js
- src/containers/ServiceReview.js
* Parse contact info from `serviceuser`, `user`, and `service` addiotionalContact values
* Fix additionalContactEmail not getting saved
* Fix additionalContact values not getting cleared out
> fix: 379 - grocery delivery contact

- src/components/ServiceReview/Childcare.js
- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/MentalHealth.js
- src/components/ServiceReview/Petcare.js
- src/constants/Routes.js
- src/containers/EmotionalFormDate.js
- src/containers/EmotionalFormType.js
- src/containers/ServiceTypeForm.js
- src/lib/utils/routes.js
- src/pages/service_type.js
* Added `:id?` param to `/service` page.
* Wired up `state.editServiceUrl` to various forms.
* Added additionalInfo cards to various review pages.
> fix: service review edit routing

- src/containers/ServiceTypeForm.js
for [ch382](https://app.clubhouse.io/helpsupply/story/382/service-type-selection-page-missing-content)
> Adjust note field by service type

- src/components/Confirmation/ContactConfirmation.js
- src/components/Dashboard/UserDashboard.js
- src/containers/GroceryFormItems.js
- src/containers/GroceryFormLocation.js
- src/containers/ServiceTypeForm.js
- src/locales/en.json
takes care of copy + form adjustments for:
- [ch390](https://app.clubhouse.io/helpsupply/story/390/grocery-confirmation-copy)
- [ch388](https://app.clubhouse.io/helpsupply/story/388/grocery-list-copy)
- [ch386](https://app.clubhouse.io/helpsupply/story/386/grocery-delivery-date-time-copy)
- [ch384](https://app.clubhouse.io/helpsupply/story/384/neighborhood-cross-street-page-copy)
- [ch378](https://app.clubhouse.io/helpsupply/story/378/service-selection-page-copy)
- [ch372](https://app.clubhouse.io/helpsupply/story/372/contact-info-confirmation-copy)
- [ch370](https://app.clubhouse.io/helpsupply/story/370/contact-info-copy)
> V1 copy updates

- src/components/Form/index.js
* Getting rid of the `Please complete form` button logic.
> fix: button labels have changed globally

- src/components/Form/CreateFormFields.js
- src/components/InputText/InputZip.js
- src/containers/ServiceLocationForm.js
- src/containers/ServiceLocationUpdateForm.js
https://app.clubhouse.io/helpsupply/story/517/mobile-switch-to-number-keyboard-for-zip-code-fields
* Added an `InputZip` component.
> fix: numeric keypad on mobile fo zip input fields

- src/components/LearnMore/Contact.js
- src/constants/Links.js
- src/locales/en.json
https://app.clubhouse.io/helpsupply/story/527/learn-more-press-kit-copy-and-link
* Add press kit to learn more section.
> fix: add presskit to learnmore

- src/components/InputText/InputZip.js
* QA reports input isn't numeric on Android. I believe this fix will work.
> fix: numeric input for android

- src/components/layouts/Page/Page.styles.js
- src/components/layouts/Page/index.js
- src/pages/dashboard.js
- src/pages/service_confirmation.js
* Remove back button on those pages.
* Add some padding to the top on mobile and tablet when pack button is off.
> fix: remove back button on dashboard and request confirm page

- src/components/Button/Button.styles.js
- src/lib/theme/radius.js
https://app.clubhouse.io/helpsupply/story/471/design-qa-change-cta-styling
> fix: updates to button styles

- src/components/InputDate/InputDate.styles.js
- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputText/InputText.styles.js
- src/containers/GroceryFormDate.js
- src/lib/theme/colors.js
https://app.clubhouse.io/helpsupply/story/447/design-qa-focused-input-field-styling
> fix: update focus styling

- src/containers/ChildcareFormDetails.js
- src/containers/LoginForm.js
- src/locales/en.json
handles the following copy updates:
- [ch393](https://app.clubhouse.io/helpsupply/story/393/welcome-back-log-in-page-copy)
- [ch401](https://app.clubhouse.io/helpsupply/story/401/child-details-copy)
- [ch421](https://app.clubhouse.io/helpsupply/story/421/emotional-support-day-time-copy)
- [ch423](https://app.clubhouse.io/helpsupply/story/423/emotional-support-details-copy)
> Copy updates

- src/components/InputDate/InputDate.styles.js
- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputText/InputText.styles.js
- src/components/Text/Text.styles.js
- src/lib/theme/space.js
https://app.clubhouse.io/helpsupply/story/453/design-qa-global-forms-and-input-fields-color-styling-spacing
> fix: tweaks to input alignments

- src/components/InputDate/InputDate.styles.js
- src/components/InputDropdown/InputDropdown.styles.js
- src/components/InputText/InputText.styles.js
https://app.clubhouse.io/helpsupply/story/453/design-qa-global-forms-and-input-fields-color-styling-spacing#activity-614
Making the actual input values gray.
> fix: make input text color gray

- src/components/Accordion/Accordion/Accordion.styles.js
- src/components/LearnMore/FAQ.js
- src/index.css
https://app.clubhouse.io/helpsupply/story/441/design-qa-learn-more-styling
> fix: font weights and learnmore design tweaks

- src/components/Card/Card.styles.js
- src/components/Card/index.js
- src/components/Confirmation/ServiceConfirmation.js
- src/components/ServiceReview/MentalHealth.js
- src/components/Services/ChildCareRequest.js
- src/components/Services/GroceryRequest.js
- src/components/Services/MentalHealthRequest.js
- src/components/Services/Request.styles.js
- src/lib/utils/strings.js
- src/locales/en.json
fixes the following tickets:
- [ch428](https://app.clubhouse.io/helpsupply/story/428/emotional-help-request-review)
- [ch390](https://app.clubhouse.io/helpsupply/story/390/grocery-confirmation-copy)
- [ch418](https://app.clubhouse.io/helpsupply/story/418/childcare-request-confirmation-copy)
- [ch430](https://app.clubhouse.io/helpsupply/story/430/emotional-support-request-confirmation-copy)
- [ch486](https://app.clubhouse.io/helpsupply/story/486/your-requests-copy)
working on social sharing issue in this ticket: [ch616](https://app.clubhouse.io/helpsupply/story/616/fix-social-share-on-samsung-galaxy)
> Copy adjustments to dashboard, service confirmation + review

- src/locales/en.json
- fixes rejected bug ticket [ch423](https://app.clubhouse.io/helpsupply/story/423/emotional-support-details-copy)
> Update titles for emotional support flow forms

- src/components/Autosuggest/Autosuggest.styles.js
- src/components/Autosuggest/index.js
- src/components/InputText/InputText.styles.js
- src/lib/theme/space.js
https://app.clubhouse.io/helpsupply/story/514/design-qa-facility-dropdown-type-styling
> fix: tweak autosuggest styles

- src/components/BackButton/BackButton.styles.js
- src/components/Header/LargeHeader.styles.js
- src/components/layouts/Page/Page.styles.js
- back button should top align with the right hand content
- fixes [ch458](https://app.clubhouse.io/helpsupply/story/458/design-qa-desktop-back-button-right-panel-content-top-alignment-on-pageload)
> Update spacing of back button

- src/components/Autosuggest/Autosuggest.styles.js
https://app.clubhouse.io/helpsupply/story/514/design-qa-facility-dropdown-type-styling
> fix: autosuggest input text color

- src/components/Header/LargeHeader.js
- src/components/Header/LargeHeader.styles.js
- src/components/layouts/Page/index.js
- fixes regression due to back button style changes, if not on home apply margin, if on home no margin top
> Fix large header margin

- src/components/InputText/InputText.styles.js
- fixes [ch484](https://app.clubhouse.io/helpsupply/story/484/design-qa-standard-input-field-border-weight)
> Update border width for text input

- src/components/Header/LargeHeader.js
- src/components/layouts/Page/index.js
> Check for back button existence

- src/locales/en.json
- fixes [ch461](https://app.clubhouse.io/helpsupply/story/461/design-qa-your-requests-contact-info-preference-capitalization)
> Fix capitalization on dashboard title

- src/components/InputText/InputZip.js
- src/components/layouts/Page/Page.styles.js
- src/components/layouts/Page/index.js
- src/lib/theme/space.js
https://app.clubhouse.io/helpsupply/story/554/design-qa-content-top-desktop
* Desktop has ~150px space at the top for inner page (non-homepage).
> fix: desktop alignment changes

- src/components/BackButton/BackButton.styles.js
- src/components/EntryContent/EntryContent.styles.js
- src/components/EntryContent/Intro.js
- src/components/Header/LargeHeader.styles.js
- src/components/layouts/Page/Page.styles.js
- src/components/layouts/Page/index.js
- src/lib/theme/space.js
https://app.clubhouse.io/helpsupply/story/632/design-qa-home-layout-mobile
Also fixing a regression in https://app.clubhouse.io/helpsupply/story/554/design-qa-content-top-desktop
> fix: layout feedback on homepage

- src/components/Confirmation/Confirmation.styles.js
- src/components/Confirmation/ConfirmationWrapper.js
- src/components/Confirmation/ServiceConfirmation.js
- src/components/Confirmation/ServiceConfirmation.styles.js
https://app.clubhouse.io/helpsupply/story/516/design-qa-request-confirmation-spacing-specs
> service confirmation styles cleanup

- src/components/ServiceReview/Childcare.js
- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/MentalHealth.js
In review form, shows additional notes or `None`. Adds this to grocery review form.
> add None if no additional notes exist

- src/containers/ServiceTypeForm.js
> fix icon/link alignment

- src/components/EntryContent/EntryContent.styles.js
- src/components/EntryContent/HowItWorks.js
- src/components/EntryContent/Intro.js
- src/components/ListLink/index.js
- src/components/layouts/Page/index.js
https://app.clubhouse.io/helpsupply/story/551/design-qa-homepage-design-specs-desktop
> fix: homepage font adjustments

- src/components/Dashboard/UserDashboard.js
- src/components/Dashboard/UserDashboard.styles.js
- src/components/layouts/Page/Page.styles.js
- src/components/layouts/Page/index.js
- src/pages/dashboard.js
- fixes [ch489](https://app.clubhouse.io/helpsupply/story/489/design-qa-your-requests-whitespace)
> User dashboard layout

- src/lib/constants/languages.js
https://app.clubhouse.io/helpsupply/story/509/design-qa-preferred-language-dropdown-option-ordering
> fix: sort languages by label

- src/components/Dashboard/UserDashboard.styles.js
https://app.clubhouse.io/helpsupply/stories/space/53/everything
* Fix margins on dashboard page. Breakpoints just needed the modified `css` import at the top.
> fix: margin on dashboard page

- functions/assets/emails/sign-in.html
fixes [ch526](https://app.clubhouse.io/helpsupply/story/526/return-user-verification-email-copy)
> Update sign in email content

- src/App.js
- src/components/Anchor/index.js
- src/components/layouts/Page/index.js
- src/constants/Routes.js
- src/locales/en.json
- src/pages/privacy.js
https://app.clubhouse.io/helpsupply/story/743/privacy-policy-link-on-homepage
* Puts a link (target='_blank') on the homepage for the privacy policy.
* Created a route and blank page for privacy policy.
> feat: privacy policy link on homepage

- src/components/Dashboard/UserDashboard.js
- src/components/ServicesList/ServicesList.styles.js
- src/components/ServicesList/index.js
https://app.clubhouse.io/helpsupply/story/672/design-qa-desktop-form-header-styling
* Applying new header text type to more pages.
> fix: new header type on more pages

- src/components/Dashboard/UserDashboard.styles.js
https://app.clubhouse.io/helpsupply/story/734/design-qa-mobile-your-requests-margins
* Margin 40px on side for mobile.
> fix: dashboard margin 40px on mobile

- src/components/Text/Text.styles.js
https://app.clubhouse.io/helpsupply/story/672/design-qa-desktop-form-header-styling
* Add media queries to new header type to revert to old style on mobile/tablet breakpoints.
> fix: adjustments to new header type

- src/components/LearnMore/About.js
- src/components/LearnMore/Contact.js
- src/components/LearnMore/LearnMore.styles.js
- adjusts spacing in about section of learn more page
- comments from [this ticket](https://app.clubhouse.io/helpsupply/story/656/design-qa-learn-more-about-us-paragraph-spacing)
> About padding on learn more page

- src/components/Dashboard/UserDashboard.js
- src/components/Dashboard/UserDashboard.styles.js
- src/components/Text/Text.styles.js
- src/components/Text/constants.js
https://app.clubhouse.io/helpsupply/story/648/design-qa-your-requests-type-and-spacing
* Added a new font style since we didn't have one that matched the rules laid out in the ticket.
> fix: dashboard contact fonts

- src/locales/en.json
https://app.clubhouse.io/helpsupply/story/706/design-qa-grocery-delivery-childcare-copy-update
> fix: cross streets copy update

- src/components/ServiceReview/ServiceReview.styles.js
https://app.clubhouse.io/helpsupply/story/788/design-qa-review-your-request-title-color
> fix: review title color

- src/containers/ServiceLocationUpdateForm.js
- src/locales/en.json
https://app.clubhouse.io/helpsupply/story/723/design-qa-want-to-update-your-zip-code-remove-copy
> fix: remove email cta

- src/components/InputDate/InputDate.styles.js
fixes [ch698](https://app.clubhouse.io/helpsupply/story/698/design-qa-grocery-delivery-date-input-field-border-weight)
> Update border width for date input

- src/components/ServicesList/ServicesList.styles.js
- src/components/ServicesList/index.js
fixes [ch639](https://app.clubhouse.io/helpsupply/story/639/design-qa-services-in-your-area-text-color-extra-horizontal-rule)
> Update organization text color in service list

- src/components/layouts/Page/Page.styles.js
- src/components/layouts/Page/index.js
- src/pages/dashboard.js
https://app.clubhouse.io/helpsupply/story/648/design-qa-your-requests-type-and-spacing
* Updated spacing on dashboard.
* Added a `noGutter` attribute as there was a 40px gutter along everything on the dashboard page.
> fix: dashboard update spacing

- src/components/layouts/Page/Page.styles.js
- src/lib/theme/colors.js
[ch784](https://app.clubhouse.io/helpsupply/story/784/accessibility-privacy-policy-link-is-very-low-contrast)
* Update copyright/privacy policy link with new 60% gray color.
> fix: link contrast

- src/components/AdditionalFormTitle/AdditionalFormTitle.styles.js
- src/components/Checkbox/Checkbox.styles.js
- src/containers/ChildcareFormOptions.js
https://app.clubhouse.io/helpsupply/story/781/design-qa-childcare-options-spacing
https://app.clubhouse.io/helpsupply/story/822/household-risk-dropdown-incorrect-default-selection
> fix: childcare options spacing and risk dropdown

- functions/assets/emails/confirmation.html
- functions/assets/emails/sign-in.html
- functions/assets/emails/welcome.html
[ch507](https://app.clubhouse.io/helpsupply/story/507/design-qa-email-type-styling)
* Fixed a typo that might improve the headers on Apple Mail.
> fix: email fonts

- src/lib/constants/urgency.js
[ch763](https://app.clubhouse.io/helpsupply/story/763/update-request-urgency-options)
* Copy updates.
> fix: update urgency options

- src/components/Confirmation/ContactConfirmation.js
- src/components/InputText/InputPhone.js
[ch756](https://app.clubhouse.io/helpsupply/story/756/design-qa-auto-format-phone-number-fields)
* Format the phone number inside the phone field.
> fix: format phone field

- src/components/Dashboard/UserDashboard.styles.js
- src/components/Services/Request.styles.js
[ch648](https://app.clubhouse.io/helpsupply/story/648/design-qa-your-requests-type-and-spacing)
> Spacing and text color on dashboard

- src/components/Card/Card.styles.js
- src/components/Card/index.js
- src/components/Confirmation/SubRow/SubRow.styles.js
- src/components/Confirmation/SubRow/index.js
- src/components/ServiceReview/Childcare.js
- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/MentalHealth.js
- src/components/ServiceReview/Petcare.js
- src/components/ServiceReview/ServiceReview.styles.js
fixes [ch700](https://app.clubhouse.io/helpsupply/story/700/design-qa-review-your-request-styling-and-spacing)
> Update service review styles

- src/components/AdditionalFormTitle/AdditionalFormTitle.styles.js
- src/containers/ChildcareFormDate.js
fixes [ch693](https://app.clubhouse.io/helpsupply/story/693/design-qa-childcare-preferred-days-times-horizontal-rule-width-and-spacing)
> Spacing in childcare date/time form

- src/containers/ServiceContactForm.js
- src/containers/ServiceTypeForm.js
- src/locales/en.json
[ch847](https://app.clubhouse.io/helpsupply/story/847/financial-assistance-checkbox)
> Financial services checkbox

- src/components/Header/Header.styles.js
- src/components/Header/index.js
- src/components/layouts/Page/index.js
[ch557](https://app.clubhouse.io/helpsupply/story/557/design-qa-progress-bar)
* Extracted progress bar into a reusable component to be used on desktop.
> Progress bar on desktop

- src/containers/GroceryFormDate.js
[ch890](https://app.clubhouse.io/helpsupply/story/890/design-qa-copy-below-this-is-a-recurring-need-is-too-close)
* Add a margin to the top of the note component.
* Fix dropdown to use `undefined` as default. (fixes initial dropdown value being selected)
> fix: recurring note too close

- src/components/StyleGuide/index.js
* `/style-guide` had several form context errors that was preventing the page from rendering.
> fix: clear out style-guide errors

- src/containers/EmotionalFormDate.js
[ch895](https://app.clubhouse.io/helpsupply/story/895/design-qa-emotional-support-flow-copy-below-this-is-a-recurring-need-is-too-close)
> fix: checkbox spacing too close

- src/components/Confirmation/SignUpConfirmation/index.js
- src/components/Confirmation/SupplyConfirmation/index.js
- src/components/Confirmation/index.js
- src/containers/AdditionalInfoForm.js
- src/containers/AvailableServices.js
- src/containers/ChildcareFormDate.js
- src/containers/ChildcareFormDetails.js
- src/containers/ChildcareFormLocation.js
- src/containers/ChildcareFormOptions.js
- src/containers/GroceryFormDate.js
- src/containers/GroceryFormItems.js
- src/containers/LoginForm.js
- src/containers/PetcareFormDate.js
- src/containers/PetcareFormDetails.js
- src/containers/ServiceContactForm.js
- src/containers/ServiceFormLocation.js
- src/containers/ServiceLocationForm.js
- src/containers/ServiceLocationUpdateForm.js
- src/containers/ServiceReview.js
- src/containers/ServiceTypeForm.js
- src/lib/constants/errors.js
- src/locales/en.json
- cleaning up our container components 🧹 
- getting large so want to get eyes on it now...more to come
> Clean up containers pt. 1

- src/containers/AdditionalInfoForm.js
- src/containers/AvailableServices.js
- src/containers/ChildcareFormDate.js
- src/containers/ChildcareFormDetails.js
- src/containers/ChildcareFormOptions.js
- src/containers/EmailForm.js
- src/containers/EmailListForm.js
- src/containers/EmotionalFormDate.js
- src/containers/EmotionalFormType.js
- src/containers/FacilityForm.js
- src/containers/GroceryFormDate.js
- src/containers/GroceryFormItems.js
- src/containers/LoginForm.js
- src/containers/PetcareFormDate.js
- src/containers/PetcareFormDetails.js
- src/containers/PetcareFormLocation.js
- src/containers/ServiceConfirmation.js
- src/containers/ServiceContactForm.js
- src/containers/ServiceFormLocation.js
- src/containers/ServiceLocationForm.js
- src/containers/ServiceLocationUpdateForm.js
- src/containers/ServiceReview.js
- src/containers/ServiceTypeForm.js
- more clean up of container files 🧹
> Clean up container files pt. 2

- src/App.js
- src/containers/ServicePaymentForm.js
- src/containers/ServiceTypeForm.js
- src/lib/constants/payment.js
- src/lib/constants/routes.js
- src/locales/en.json
- src/pages/service_payment.js
- add preferred payment step to flow
> Add preferred payment step to flow

- src/components/Confirmation/ServiceConfirmation/index.js
- src/components/FormPrivacyNode/FormPrivacyNode.js
- src/components/LearnMore/FAQ.js
- src/components/ServiceReview/Childcare.js
- src/components/ServiceReview/Grocery.js
- src/components/ServiceReview/MentalHealth.js
- src/components/ServiceReview/ServiceReview.styles.js
- src/containers/ServicePaymentForm.js
- src/containers/ServiceReview.js
- src/locales/en.json
- src/state/persistState.js
[ch908](https://app.clubhouse.io/helpsupply/story/908/add-payment-method-to-request-review-and-confirmation)
[ch906](https://app.clubhouse.io/helpsupply/story/906/add-invisible-hands-disclaimer-language-to-request-review)
* Refactored `mapServiceToName` to not be a method (unnecessary).
* Refactored `FormPrivacyNode`'s custom markdown renderer in-leiu of using the built-in `linkTarget` prop on react-markdown.
* Same with `FAQ`'s custom markdown renderer.
* Added payment info to 'Review your request' page.
* Added `editServiceUrl` redirect handling for the `ServicePaymentForm` container.
* If organization has a `Disclaimer` prop, show that instead of the default on `ServiceReview` container.
* Remove console.log
> feat: invisible hands disclaimer, payment review
