src/App.js
src/components/StyleGuide.js
src/components/Text/Text.js
src/components/Text/Text.styles.js
src/index.css

- creates a text component
- `type` prop allows you to choose a text style - `HEADER_1` - `HEADER_4`, `BODY_1` + `BODY_2`, and `NOTE`
- `as` prop defines the text element used - `p`, `h1`, `h2`, `h3`, `h4`
- sets up a simple style guide page as a reference of all of our styled components
- imports inter google font and changes font globally
- removes unused code style

Text component + styles

---

src/components/TextArea/TextArea.styles.js
src/components/TextArea/index.js

In my last PR Git didn't pick up the case sensitive file name changes. The only change here is renaming the directory to `TextArea` and `TextArea.styles.js`. No changes were made to the code.

fix(TextArea): case sensitive file name update

---

src/lib/firebaseBackend.js

Resolving these promises when the backend detects missing parameters makes the front-end believe the request has been successful which is causing a few issues. Rejecting the promise let's us know an error has occurred in a dependable manner.

fix(backend): use promise.reject for errors instead of resolving

---

package.json
src/constants/breakpoints.js
src/lib/utils/media-queries.js
src/pages/entry.js
yarn.lock

Issue #112 
- Installed [facepaint](https://emotion.sh/docs/media-queries#facepaint) to utilize responsive styles
- Created constants for breakpoints
- Set up utility for media-queries
**Testing:**
- Replace `css` import from `@emotion/core` with the new utility
- Use array in place of singular value `['pink', 'blue', 'green', 'yellow']`
Note: I copied over some values for breakpoints from another project. Happy to change these up if others have opinions. Just needed to get some media-queries in place to start working on the desktop design for start page.

chore(media-queries): setup facepaint and media queries utility

---

src/components/InputDropdown/InputDropdown.styles.js
src/components/InputDropdown/index.js
src/components/StyleGuide/index.js
src/containers/FacilityForm.js
src/containers/SupplyForm.js

* Clicking right on the arrow icon doesn’t open the dropdown (need pointer-events: none).
* The label doesn’t transition up into the corner like on see on the other inputs.
* Added focus border as seen on other inputs.

Improve the ui of the dropdown

---

src/components/Form/CreateForm.js
src/components/Form/CreateFormFields.js
src/components/Form/Form.styles.js
src/components/Form/FormBuilder.js
src/components/Form/index.js
src/components/InputDropdown/InputDropdown.styles.js
src/components/InputDropdown/index.js
src/components/InputText/InputText.styles.js
src/components/InputText/index.js
src/containers/FacilityForm.js
src/locales/en.json

Closes #106 
The new Need Services flow is going to require a handful of forms that will include a series of unique imports with some level of dynamic changes (if you change a service type the form fields will change). In an attempt to save some work laying out a bunch of form fields we're adding a utility that accepts an array of objects, each of which can be used to define an input.
This is likely to change over time, initially when we merge Izzy's Smart Forms PR and more often as we expand the functionality of each input type.
Note: I'll add this to all the forms once Izzy's PR is merged and the current form work stabilizes a bit.
I'll add some notes throughout.

feat(forms): introduces CreateForm and CreateFormFields utilities

---

src/lib/utils/routes.js

A little tweak to the `routeWithParams` utility.

fix(routing): return undefined if no param match

---

src/components/Autosuggest/Autosuggest.styles.js
src/components/Form/CreateFormFields.js
src/components/Form/HeaderInfo.js
src/components/TextArea/TextArea.styles.js
src/containers/DropSiteForm.js
src/containers/EmailForm.js
src/containers/FacilityForm.js
src/containers/SupplyForm.js

- Moved container forms to `<FormBuilder />`
- Added support for `TextArea` & `Checkbox`
- Added `NODE` type to allow for injection of content nodes (or anything else that is needed).

chore(forms): use FormBuilder where applicable

---

firestore.rules
src/App.test.js
src/lib/firebaseBackend.js

This allows users to create requests before they are validated. Once we validate their email domains (if they aren't already validated) then the requests appear with a `valid` property equal to `true.`
This diff comes with tests to assert that the behavior is correct.

Added request validation

---

src/components/HCPSignupFinish.js
src/constants/Routes.js
src/containers/FindFacility.js
src/lib/firebaseBackend.js
src/pages/dropsite_contact.js

When a facility dropsite does not exist in our database but does exist in the hospital index we want to create a placeholder dropsite with the facility ID. If it does not exist in the hospital index it will generate a unique id.
From there we route accordingly if the user is logged in or not, and whether the dropsite has requests or not.
@newhouseb is currently working on permissions so this flow might need to be adjusted

fix routing and placholder dropsite creation

---

src/App.js
src/components/Confirmation/FacilityConfirmation.js
src/constants/Routes.js
src/containers/FacilityForm.js
src/i18n.js
src/pages/facility_confirmation.js
src/pages/facility_edit.js
src/pages/facility_new.js

Closes this https://app.clubhouse.io/helpsupply/story/33/move-edit-facility-screen-to-unique-route
Makes progress on this https://app.clubhouse.io/helpsupply/story/34/move-confirmation-screens-to-unique-routes
Here we are adding unique routes for the facility confirmation and edit screens which allows for the page navigation to work a bit better (you can refresh or go back successfully now). I also moved the facility form logic into that container component instead of the facility page.

chore(facility): add pages for facility confirmation and edit

---

src/lib/backendInterface.js
src/lib/firebaseBackend.js

Syntax update to clear out some error reporting warnings.

Chore: no-throw-literal warnings

---

src/App.js
src/constants/Routes.js
src/containers/EmailForm.js
src/locales/en.json
src/pages/signup.js
src/pages/signup_confirmation.js

More progress here: https://app.clubhouse.io/helpsupply/story/34/move-confirmation-screens-to-unique-routes
Adds unique route for signup confirmation. Also exchanges the `withRouter` HOC for `useHistory` and `useParams` hooks (which I've been doing everywhere).

chore(signup): add signup confirmation screen

---

src/components/Autosuggest/Autosuggest.styles.js

Just squashing a warning. Verified that overflowScroll still works on the AutoSuggest component for the facility page.

Chore: remove kebab-case warning

---

src/App.js
src/constants/Routes.js
src/containers/FacilityForm.js
src/pages/facility_confirmation.js
src/pages/facility_edit.js
src/state/StateProvider.js
src/state/persistState.js
src/state/reducer.js

We're using a combination of context and hooks to maintain a simple global state that is a little reduxy. This includes a little bit of middleware to persist our state data to localhost. That part is fairly bare at this point and we need to give some thought to what data we want to persist and when we should clear it, but the outline of an idea is in here.
fetch state:
`const [ state ] = useStateValue();` or `const [{ pieceOfState }] = useStateValue();`
set state:
```
import { useStateValue, actions } from 'state/StateProvider';
function MyComponent() {
const dispatch = useStateValue()[1]; OR const [state, dispatch] = useStateValue();
{...more code and stuff}
const handleSomeAction = () => {
...doing some stuff
dispatch({
type: actions.ADD_PENDING_FACILITY,
pendingFacility: { ...data }, …
```

feat(state): add simple state machine

---

src/components/HCPSignupFinish.js
src/hooks/useLoggedIn.js
src/lib/firebaseBackend.js
src/locales/en.json

Sort of related to this:
https://app.clubhouse.io/helpsupply/story/29/loading-screen-logging-you-in-screen
Did some refactoring for the `signup/finish` url that get's emailed to you and learned a few things. This could probably be further broken out into more components and pages, but wanted to get the progress up here for discussion/feedback.
* When you submit your email from the supply signup page (e.g. `signup/50441`) a localStorage object `emailForSignIn` gets saved
* When click the link in your email, you go to the `signup/finish` page
* If you're completing this process on a different browser, or for some reason the localStorage object isn't set, you're prompted to enter your email again "Please enter your email, once more"
* Added some error handling to the `continueSignup` method …

Refactor: signup finish page

---

src/App.js
src/components/HCPSignupFinish.js
src/hooks/useAuth.js

Related to this:
https://app.clubhouse.io/helpsupply/story/29/loading-screen-logging-you-in-screen
* Updated `ProtectedRoute` to use the `useLoggedIn` hook.
* Once the app connects to the backed (`useLoggedIn -> loaded`) and if the `loggedIn` status is false, redirect the user to `HOME`.

Check logged-in state using hook, redirect to home if not logged in

---

src/components/HCPSignupFinish.js
src/lib/firebaseBackend.js

https://app.clubhouse.io/helpsupply/story/95/blank-drop-off-location-page
A previous change was sending logged-in users to the dropsite admin page which isn't totally correct. 
* If a facility doesn't have a dropsite yet, send them to the `new dropsite page`. 
* If a dropsite exists be there are no requests, send them to the `new supplies request page`.
* Otherwise, send them to the `admin page`.

Fix: remove simplistic already logged-in effect, use routing logic

---

src/components/Autosuggest/index.js
src/containers/FindFacility.js

In local development on the `/request` page, this fix clears `Warning: Failed prop type: 'onSuggestionsClearRequested' must be implemented.`

Fix onSuggestionsClearRequested warning

---

src/containers/FindFacility.js

The previous `onSuggestionsClearRequested` fix actually gets called everytime the autosuggest drawer closes, so clearing the state broke the page. It's a required function for that component, so a `null` return function solves the warning, and we don't need to do anything special when the drawer closes.

Fix onSuggestionsClearRequested warning - part 2

---

src/constants/Routes.js
src/containers/AdditionalInfoForm.js
src/containers/GroceryFormDate.js
src/containers/GroceryFormItems.js
src/containers/GroceryFormLocation.js
src/containers/ServiceTypeForm.js
src/lib/firebaseBackend.js
src/pages/service_grocery.js

Similarly to the old create dropsite flow, we create a blank service request when a user begins the service form flow, starting with `kind` and `urgency`. From there we update the service through the grocery form (location, date, items, notes) and will eventually send the user to the "review request" page.
This also adds an id param to the additional info page so we can look a service up and update from there.
Seems a little repetitious to have a review then submit request page since we are actually saving it behind the scenes but because everything lives on a separate page this is the easiest option for the time being.
It's still not clear to me how we determine which fulfillment organization should be assigned as we create a request so in the meantime i've added a placeholder string. …

Save grocery service as user navigates form

---

src/components/Form/CreateFormFields.js
src/components/InputDate/InputDate.js
src/components/InputDropdown/index.js
src/components/InputText/index.js
src/containers/AdditionalInfoForm.js
src/containers/ChildcareFormLocation.js
src/containers/ChildcareFormOptions.js
src/containers/EmotionalFormDate.js
src/containers/EmotionalFormType.js
src/containers/GroceryFormDate.js
src/containers/GroceryFormItems.js
src/containers/GroceryFormLocation.js
src/containers/PetcareFormLocation.js
src/containers/ServiceContactForm.js
src/pages/service_additional_info.js
src/pages/service_childcare.js
src/pages/service_emotional.js
src/pages/service_grocery.js
src/pages/service_petcare.js

https://app.clubhouse.io/helpsupply/story/152/optional-fields-are-returning-an-error-when-not-filled-out
https://app.clubhouse.io/helpsupply/story/27/review-form-validation
https://app.clubhouse.io/helpsupply/story/151/mobile-not-able-to-bypass-additional-contact-person-forms
https://app.clubhouse.io/helpsupply/story/160/additional-info-field-during-grocery-flow-not-optional
* Setup validation and isRequired correctly on each page.
* When conditionally rendering in React, InputText and InputDropdown weren't calling `register` from `react-hook-form`. An example of this is the contact form on http://localhost:3000/service/grocery/location/Jb0LTFNxnp5mAavJI0q2 
* Solution was to wrap those components in react-hook-form's `Controller` component, which handles loading and unloading. It expects …

Validation tweaks

---

src/components/AdditionalFormTitle/AdditionalFormTitle.js
src/containers/ChildcareFormDetails.js
src/containers/PetcareFormDetails.js

* The repeating fields on pages like `http://localhost:3000/service/childcare/details/RlH99jLBAP9WEP5jf7js` needed some TLC to get wired up.

fix: wire-up childcare and petcare repeating fields

---

src/constants/Routes.js
src/containers/ServiceReview.js
src/lib/utils/services.js

https://app.clubhouse.io/helpsupply/story/233/set-revicerequest-status-to-open-when-submitting-on-the-review-submit-page
* Slightly rearranged routes file to mimic our current flow logic.
* Wired up a `updateServiceRequest` to `ServiceReview` page to set `status: open` on a `servicerequest` record.
* Remove petcare from serviceOptions dropdown.

feat: servicerequest status set to open when submitting

---

src/components/ServicesList/index.js
src/components/SignupFinish.js
src/constants/Routes.js
src/containers/AvailableServices.js
src/containers/EmailForm.js
src/containers/ServiceContactForm.js
src/containers/ServiceLocationForm.js
src/lib/firebaseBackend.js
src/lib/utils/routes.js

https://app.clubhouse.io/helpsupply/story/227/save-zip-code-value-to-user-and-request
https://app.clubhouse.io/helpsupply/story/247/zip-code-qualification-form-integration
* On the `SERVICE_LOCATION` page, hooked up `getServicesForZip`.
* If no services available, redirect to 'no results for zip' page.
* If services available, store the zip and redirect to 'zip results' aka (`SERVICE_LOCATION_AVAILABLE`) page.
* Only show relevant services on the 'zip results' page.
* Zip results page accepts a zip in the url as well as localStorage, redirects you out of there if either zip is neither present nor valid.
* Zip data get passed over to the email signup/login link.
* Zip data persists until the `/contact` page, where it finally get stored to the user.

feat: integrate zips

---

src/App.js
src/components/Confirmation/ConfirmationWrapper.js
src/constants/Routes.js
src/containers/EmailListForm.js
src/locales/en.json
src/pages/email_list_confirmation.js
src/pages/service_location_unavailable.js

- if zip code entered is not valid, send user to unavailable page w/ email list sign up
- upon submitting email list sign up, route user to a confirmation page for the email list
- add `noIcon` prop to confirmation wrapper

Non supported zip code flow setup

---

src/components/Confirmation/OrganizationConfirmation.js
src/components/Confirmation/ServiceConfirmation.js
src/lib/organizations/details.js
src/locales/en.json

- add organization emails + adjust website data
- check for email before displaying that field (manyc doesn't have a support email)
- add map service to name that fixes the display of the service name

Update data on service confirmation page

---

src/containers/ChildcareFormDate.js
src/containers/PetcareFormDate.js

https://app.clubhouse.io/helpsupply/story/270/when-do-you-need-service-is-no-longer-required
* Wire-up `disabled` state to two groups of checkboxes on petcare and childcare.

fix: required fields on petcare and childcare

---

src/components/InputDropdown/index.js

https://app.clubhouse.io/helpsupply/story/273/pet-care-childcare-editing-pet-or-child-2-3-etc-details-changes-the-first-pet-in-the-list
* Changing a dropdown value for something like `Child 2` or `Child 3` was updating the displayed value for child 1 because of duplicate name value. Solution it to use `customkey`.

fix: dropdown values for repeating fields have duplicate name values

---

src/components/InputDate/InputDate.js

disallows typing into date input field and saves date as a "MMMM D, YYYY" format instead of timestamp

date picker changes 

---

src/App.js

Just noticed the `backend` prop was missing on the `Login` page.

fix: pass backend prop to login page

---

src/components/InputDate/InputDate.js
src/index.css

for some reason height: 100% doesn't work on ios so we need to set it to min-height to correctly span the content.
i'm not sure if this is related to the other mobile layout bugs yet
height: 100%:
min-height: 100%

Layout fix

---

src/containers/ServiceReview.js

* Use pretty name for organization data in email.
* Use timeCreated for childcare forms where Date isn't specified.
* Cast number of children to String so detail formatting doesn't break.
* Add 'Preferred days' to childcare details.

fix: child email confirmation data, email organization name

---

src/components/ServiceReview/Grocery.js
src/lib/utils/datetime.js

* Date format was returning the week of the year (i.e. the 52nd for last week of year) rather than the day of the month (i.e. 1st, 2nd, etc.)

fix: delivery date format

---

src/containers/ChildcareFormDetails.js

* Wire up 'disabled' logic to birthYear and birthMonth fields on childcare details page.

fix: update disabled logic for childcare optional fields

---

src/components/Checkbox/Checkbox.styles.js

https://app.clubhouse.io/helpsupply/story/477/design-qa-childcare-form-content-order-spacing
* Added 25px margin-bottom to checkboxes. Verified this fix works on other instances of the checkbox.

fix: checkbox bottom margin

---

src/components/Header/LargeHeader.js
src/components/Header/LargeHeader.styles.js
src/components/layouts/Page/Page.styles.js

https://app.clubhouse.io/helpsupply/story/681/design-qa-desktop-logo-placement
* Current desktop logo is '75%' percent from the top, which is all over the place.
* This places the desktop logo at the 'end' of the container, 150px from the bottom.

fix: desktop logo placement

---

src/containers/ChildcareFormOptions.js

https://app.clubhouse.io/helpsupply/story/643/design-qa-childcare-options-covid-learn-more-link-spacing
* Add spacing below the 'learn more' node.

fix: add spacing on childcare options learnmore component

---

src/containers/GroceryFormLocation.js
src/locales/en.json

https://app.clubhouse.io/helpsupply/story/570/design-qa-groceries-additional-contact-contact-preference
* Set email field as required when contactPreference is set to email.

feat: set email to required when set as a contact preference

---

src/components/HomePage/HomePage.styles.js

https://app.clubhouse.io/helpsupply/story/444/design-qa-homepage-alignment-desktop
* Adding a dividing line down the center of the homepage.

feat: add dividing line to homepage

---

src/containers/ServiceTypeForm.js

https://app.clubhouse.io/helpsupply/story/802/mobile-service-urgency-drop-downs-don-t-set-top-selection-unless-you-select-another-then-go-back
* Dropdowns broken on `/service` page.

fix: dropdown options in services broken

---

src/components/Loader/PageLoader.styles.js

https://app.clubhouse.io/helpsupply/story/738/design-qa-loading-animation-width
* Final sizes are different than what is requested in the ticket to accomodate lottie margins. See screencap demoing margins in lottie file.

fix: page loader size

---

src/components/Confirmation/ServiceConfirmation.styles.js
src/components/Confirmation/SignUpConfirmation.js
src/components/Confirmation/SignUpConfirmation.styles.js
src/locales/en.json

https://app.clubhouse.io/helpsupply/story/691/design-qa-thank-you-confirmation-type-styles-spacing-and-copy
* Verify fonts and colors for thank you signin page.
* Fix a word-break issue on service confirmation page.

fix: add new note to thank you screen

---

src/components/Confirmation/ServiceConfirmation.js

[ch616](https://app.clubhouse.io/helpsupply/story/616/fix-social-share-on-samsung-galaxy)
* Test for `navigator.share` or `navigator.clipboard` and hide if neither are present.

fix: hide share link if browser doesn't support sharing or clipboard functionality

---

src/containers/ChildcareFormLocation.js

[ch878](https://app.clubhouse.io/helpsupply/story/878/childcare-flow-neighborhood-selection-does-not-allow-for-first-option-unless-user-picks-another-then-goes-back)

fix: childcare location dropdown

---

src/containers/ServiceReview.js

[ch897](https://app.clubhouse.io/helpsupply/story/897/confirmation-email-shows-incorrect-added-date)

fix: confirmation email has wrong date

---

src/App.styles.js
src/components/Header/Header.styles.js
src/components/layouts/Page/Page.styles.js
src/components/layouts/Page/index.js

* On desktop, the progress-bar was behind form elements. This PR moves the progress-bar farther down the html content stack, since z-index doesn't affect `position: fixed` in the this case.
* Prevent scroll bounce on desktop because the progress-bar was jumping out in a visually strange way.

fix: progressbar z-index, scroll-bounce

---

src/components/Confirmation/ServiceConfirmation/ServiceConfirmation.styles.js

* Button styles on the `/service/confirmation` screen were slightly different.
Different `border-radius` ↓
Fixed ↓

fix: service confirmation button styles

---

src/containers/ServiceTypeForm.js

* Removing the financial assistance checkbox from the service type page.
* Update Note padding now that checkbox is gone.

feat: removing financial assistance checkbox from service page

---

src/components/LearnMore/FAQ.js
src/components/LearnMore/LearnMore.styles.js
src/components/LearnMore/Partners.js
src/locales/en.json
src/pages/learn_more.js

* Added 'Invisible Hands' to 'Does Help Supply provide the volunteer services?' section of FAQ.
* Added 'Invisible Hands' to 'Our Partners' section of 'About HS'.
* ~Noticed `learn-more` pages has a backButton on desktop and no backButton on mobile. Extended `hasBackButton` prop to include mobile and desktop declarations.~ Took out backButton on 'learn-more' pages.
* Updated `text-underline: none` on FAQ links.

feat: updates to partner info on learn more page

---

src/locales/en.json

* Remove trailing slash from Invisible Hands partner url.
old ↓
new ↓

fix: remove trailing slash from new partner url
